### ISSUE TITLE
Return Value Error

### ISSUE THREAD

**Issue by xiaohu714** [seokhokang/reaction_yield_nn#2]
Hello!

I encountered an issue when I tried to run the code. The issue is listed below, it seems python cannot return *value?

"""
reaction_yield_nn/util.py", line 11  
  return *gs, labels
           ^
SyntaxError: invalid syntax
"""

FYI, I'm using dgl-0.6.0, python-3.6.13.

**Comment by seokhokang** [comment]
I was able to run the code on my PC without any issues.

**Comment by xiaohu714** [comment]
Can you please send me a copy of the packages and their version?

**Comment by seokhokang** [comment]
Unpacking (return *gs, labels) does not work in Python 3.6. Recommended to use a more recent Python version.

**Comment by xiaohu714** [comment]
OK, I'll try it out.
